2024-06-14 19:25:16,070 [INFO] Setting webhook
2024-06-14 19:25:16,436 [INFO] Webhook set
2024-06-14 19:27:41,319 [INFO] 127.0.0.1 [14/Jun/2024:14:27:40 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:27:54,511 [INFO] 127.0.0.1 [14/Jun/2024:14:27:54 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:27:57,135 [INFO] 127.0.0.1 [14/Jun/2024:14:27:56 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:28:25,767 [INFO] 127.0.0.1 [14/Jun/2024:14:28:25 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:28:27,474 [INFO] 127.0.0.1 [14/Jun/2024:14:28:27 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:28:40,595 [INFO] 127.0.0.1 [14/Jun/2024:14:28:38 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:28:44,663 [INFO] 127.0.0.1 [14/Jun/2024:14:28:44 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:28:56,028 [INFO] 127.0.0.1 [14/Jun/2024:14:28:56 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:29:07,167 [ERROR] Traceback (most recent call last):
  File "D:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\handlers\message_handler.py", line 119, in make_admin
    args = message.text.split()[1]
           ~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

2024-06-14 19:29:07,168 [INFO] 127.0.0.1 [14/Jun/2024:14:29:07 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:29:17,151 [ERROR] Traceback (most recent call last):
  File "D:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\handlers\message_handler.py", line 119, in make_admin
    args = message.text.split()[1]
           ~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

2024-06-14 19:29:17,154 [INFO] 127.0.0.1 [14/Jun/2024:14:29:17 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:29:22,934 [INFO] 127.0.0.1 [14/Jun/2024:14:29:22 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:29:26,133 [INFO] 127.0.0.1 [14/Jun/2024:14:29:26 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:29:42,730 [INFO] 127.0.0.1 [14/Jun/2024:14:29:42 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:29:54,843 [INFO] 127.0.0.1 [14/Jun/2024:14:29:54 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:29:58,033 [INFO] 127.0.0.1 [14/Jun/2024:14:29:57 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:31:26,575 [INFO] User (, Queeenace, 458911009) tries to log in
2024-06-14 19:31:27,389 [ERROR] Traceback (most recent call last):
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\handlers\message_handler.py", line 72, in start
    await bot.send_message(message.chat.id, messages.qr_code_view, reply_markup=km.getQRViewKeyboard())
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\bot\bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\bot\api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 141, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Inline keyboard button web app url 'http://127.0.0.1:8000/bot/qr' is invalid: only https links are allowed

2024-06-14 19:31:27,568 [INFO] 127.0.0.1 [14/Jun/2024:14:31:26 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:31:35,098 [INFO] 127.0.0.1 [14/Jun/2024:14:31:34 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:31:37,176 [INFO] 127.0.0.1 [14/Jun/2024:14:31:37 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:31:39,354 [INFO] 127.0.0.1 [14/Jun/2024:14:31:39 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:31:40,841 [INFO] 127.0.0.1 [14/Jun/2024:14:31:40 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:31:41,905 [ERROR] Traceback (most recent call last):
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\handlers\message_handler.py", line 333, in qr_request
    await bot.send_message(chat_id, messages.qr_code_view, reply_markup=km.getQRViewKeyboard())
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\bot\bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\bot\api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 141, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Inline keyboard button web app url 'http://127.0.0.1:8000/bot/qr' is invalid: only https links are allowed

2024-06-14 19:31:41,962 [INFO] 127.0.0.1 [14/Jun/2024:14:31:41 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:38:40,819 [ERROR] Traceback (most recent call last):
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\handlers\message_handler.py", line 333, in qr_request
    await bot.send_message(chat_id, messages.qr_code_view, reply_markup=km.getQRViewKeyboard())
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\bot\bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\bot\api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 141, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Inline keyboard button web app url 'http://127.0.0.1:8000/bot/qr' is invalid: only https links are allowed

2024-06-14 19:38:40,877 [INFO] 127.0.0.1 [14/Jun/2024:14:38:40 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:40:58,644 [INFO] 127.0.0.1 [14/Jun/2024:14:40:57 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:41:20,491 [ERROR] Traceback (most recent call last):
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\handlers\message_handler.py", line 333, in qr_request
    await bot.send_message(chat_id, messages.qr_code_view, reply_markup=km.getQRViewKeyboard())
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\bot\bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\bot\api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "d:\Users\sturo_gpmk3vo\programming\Unlock\smena\telegram-bot\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 141, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Inline keyboard button web app url 'http://127.0.0.1:8000/bot/qr' is invalid: only https links are allowed

2024-06-14 19:41:20,551 [INFO] 127.0.0.1 [14/Jun/2024:14:41:20 +0000] "POST /bot/ HTTP/1.1" 200 153 "-" "-"
2024-06-14 19:43:52,539 [WARNING] Shutting down..
2024-06-14 19:43:53,332 [WARNING] Bye!
2024-06-14 19:43:53,333 [INFO] DB connection closed
